# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fullstackfrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_180cf1230d1e4b599928ed1b9645ab49 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b9631c8f21974fa5870f539d1b0e1c5a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_180cf1230d1e4b599928ed1b9645ab49 }}/fullstackfrontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fullstackfrontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_17d3b2b41cee4a74925afc9d9eb2cf8b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_180cf1230d1e4b599928ed1b9645ab49 }}/fullstackfrontend:${{ github.sha }}'